sector = {}

sector[0]  = {"sector": "undefined",
            0:  "undefined"}
sector[1]  = {"sector": "Basic Materials",
            0:  "undefined",
            1:  "Agricultural Inputs",
            2:  "Building Materials",
            3:  "Chemicals",
            4:  "Specialty Chemicals",
            5:  "Lumber & Wood Production",
            6:  "Paper & Paper Products",
            7:  "Aluminum",
            8:  "Copper",
            9:  "Other Industrial Metals & Mining",
            10: "Gold",
            11: "Silver",
            12: "Other Precious Metals & Mining",
            13: "Coking Coal",
            14: "Steel"}
sector[2]  = {"sector": "Consumer Cyclical",
            0:  "undefined",
            1:  "Auto & Truck Dealerships",
            2:  "Auto Manufacturers",
            3:  "Auto Parts",
            4:  "Recreational Vehicles",
            5:  "Furnishings, Fixtures & Appliances",
            6:  "Residential Construction",
            7:  "Textile Manufacturing",
            8:  "Apparel Manufacturing",
            9:  "Footwear & Accessories",
            10: "Packaging & Containers",
            11: "Personal Services",
            12: "Restaurants",
            13: "Apparel Retail",
            14: "Department Stores",
            15: "Home Improvement Retail",
            16: "Luxury Goods",
            17: "Internet Retail",
            18: "Specialty Retail",
            19: "Gambling",
            20: "Leisure",
            21: "Lodging",
            22: "Resorts & Casinos",
            23: "Travel Services"}
sector[3]  = {"sector": "Financial Services",
            0:  "undefined",
            1:  "Asset Management",
            2:  "Banks - Diversified",
            3:  "Banks - Regional",
            4:  "Mortgage Finance",
            5:  "Capital Markets",
            6:  "Financial Data & Stock Exchanges",
            7:  "Insurance - Life",
            8:  "Insurance - Property & Casualty",
            9:  "Insurance - Reinsurance",
            10: "Insurance - Specialty",
            11: "Insurance Brokers",
            12: "Insurance - Diversified",
            13: "Shell Companies",
            14: "Financial Conglomerates",
            15: "Credit Services"}
sector[4]  = {"sector": "Real Estate",
            0:  "undefined",
            1:  "Real Estate - Development",
            2:  "Real Estate Services",
            3:  "Real Estate - Diversified",
            4:  "REIT - Healthcare Facilities",
            5:  "REIT - Hotel & Motel",
            6:  "REIT - Industrial",
            8:  "REIT - Office",
            9:  "REIT - Residential",
            10: "REIT - Retail",
            11: "REIT - Mortgage",
            12: "REIT - Specialty",
            13: "REIT - Diversified"}
sector[5]  = {"sector": "Consumer Defensive",
            0:  "undefined",
            1:  "Beverages - Brewers",
            2:  "Beverages - Wineries & Distilleries",
            3:  "Beverages - Non-Alcoholic",
            4:  "Confectioners",
            5:  "Farm Products",
            6:  "Household & Personal Products",
            7:  "Packaged Foods",
            8:  "Education & Training Services",
            9:  "Discount Stores",
            10: "Food Distribution",
            11: "Grocery Stores",
            12: "Tobacco"}
sector[6]  = {"sector": "Healthcare",
            0:  "undefined",
            1:  "Biotechnology",
            2:  "Drug Manufacturers - General",
            3:  "Drug Manufacturers - Specialty & Generic",
            4:  "Healthcare Plans",
            5:  "Medical Care Facilities",
            6:  "Pharmaceutical Retailers",
            7:  "Health Information Services",
            8:  "Medical Devices",
            9:  "Medical Instruments & Supplies",
            10: "Diagnostics & Research",
            11: "Medical Distribution"}
sector[7]  = {"sector": "Utilities",
            0:  "undefined",
            1:  "Independent Power Producers",
            2:  "Renewable",
            3:  "Regulated Water",
            4:  "Regulated Electric",
            5:  "Regulated Gas",
            6:  "Diversified"}
sector[8]  = {"sector": "Communication Services",
            0:  "undefined",
            1:  "Telecom Services",
            2:  "Advertising Agencies",
            3:  "Publishing",
            4:  "Broadcasting",
            5:  "Entertainment",
            6:  "Internet Content & Information",
            7:  "Electronic Gaming & Multimedia"}
sector[9]  = {"sector": "Energy",
            0:  "undefined",
            1:  "Oil & Gas Drilling",
            2:  "Oil & Gas E&P",
            3:  "Oil & Gas Integrated",
            4:  "Oil & Gas Midstream",
            5:  "Oil & Gas Refining & Marketing",
            6:  "Oil & Gas Equipment & Services",
            7:  "Thermal Coal",
            8:  "Uranium"}
sector[10] = {"sector": "Industrials",
            0:  "undefined",
            1:  "Aerospace & Defense",
            2:  "Specialty Business Services",
            3:  "Consulting Services",
            4:  "Rental & Leasing Services",
            5:  "Security & Protection Services",
            6:  "Staffing & Employment Services",
            7:  "Conglomerates",
            8:  "Engineering & Construction",
            9:  "Infrastructure Operations",
            10: "Building Products & Equipment",
            11: "Farm & Heavy Construction Machinery",
            12: "Industrial Distribution",
            13: "Business Equipment & Supplies",
            14: "Specialty Industrial Machinery",
            15: "Metal Fabrication",
            16: "Pollution & Treatment Controls",
            17: "Tools & Accessories",
            18: "Electrical Equipment & Parts",
            19: "Airports & Air Services",
            20: "Airlines",
            21: "Railroads",
            22: "Marine Shipping",
            23: "Trucking",
            24: "Integrated Freight & Logistics",
            25: "Waste Management"}
sector[11] = {"sector": "Technology",
            0:  "undefined",
            1:  "Information Technology Services",
            2:  "Software - Application",
            3:  "Software - Infrastructure",
            4:  "Communication Equipment",
            5:  "Computer Hardware",
            6:  "Consumer Electronics",
            7:  "Electronic Components",
            8:  "Electronics & Computer Distribution",
            9:  "Scientific & Technical Instruments",
            10: "Semiconductor Equipment & Materials",
            11: "Semiconductors",
            12: "Solar"}

def get(code, field, sector=sector):
    return sector[code]["sector"] + " > " + sector[code][field]